 SELECT LONGITUDE,LATITUDE FROM AVL_Data_Hist_02  WHERE (BUS_REGISTRATION_NO = 'W1048S' OR BUS_ID = 'W1048S')  AND gps_datetime BETWEEN '17-Dec-2015 7:00 AM' AND '17-Dec-2015 8:00 AM'  ORDER BY GPS_DATETIME
 SELECT top 100 BUS_REGISTRATION_NO,gps_datetime FROM AVL_Data_Hist_08 where BUS_REGISTRATION_NO is not null
 -- add with (nolock)