 SELECT distinct RP.DESCRIPTION,BUS.BUS_ID,BUS.VEHICLE_PLATE_NO,CONVERT(varchar(12),BA.TRIGGER_DATETIME, 108) as TRIGGER_DATETIME,BA.STATUS 
 FROM 
 --(SELECT CODE FROM ALARM_PROFILE) AP, 
 --(SELECT STATUS,TRIGGER_DATETIME,BUS_ID,DIRECTION,ALARM_TYPE,ROUTE_ID FROM BUS_ALARM WITH (NOLOCK) WHERE Trigger_Datetime>DATEADD(d,0,DATEDIFF(d,0,GETDATE())) ) BA, 
 (SELECT STATUS,TRIGGER_DATETIME,BUS_ID,DIRECTION,ALARM_TYPE,ROUTE_ID FROM BUS_ALARM WITH (NOLOCK) WHERE Trigger_Datetime>'2015-12-14' ) BA, 
 (SELECT BUS_ID,VEHICLE_PLATE_NO FROM BUS_PROFILE) BUS, 
 (SELECT DESCRIPTION,ROUTE_ID,DIRECTION FROM ROUTE_PROFILE) RP 
 --WHERE BA.ALARM_TYPE = AP.CODE 
 WHERE 
 --AND
  BA.BUS_ID = BUS.BUS_ID 
 AND BA.ROUTE_ID=RP.ROUTE_ID 
 AND BA.DIRECTION = RP.DIRECTION  
 AND CONVERT(VARCHAR(10), BA.TRIGGER_DATETIME, 105) = CONVERT(VARCHAR(10), GETDATE(), 105) 
 AND TRIGGER_DATETIME = (SELECT MAX(TRIGGER_DATETIME) FROM BUS_ALARM WITH (NOLOCK) WHERE ALARM_TYPE=BA.ALARM_TYPE AND BUS_ID=BA.BUS_ID) 
 --AND BA.STATUS <> 'R' AND BA.STATUS <> 'A' 
 AND BA.STATUS NOT IN ('R','A')
 --AND BA.ALARM_TYPE='IDLE'
 AND BA.ALARM_TYPE='COVEROPEN'
 
 --select MIN(trigger_datetime)[min],MAX(trigger_datetime)[max] from Bus_Alarm with (nolock)
 --where ALARM_TYPE='COVEROPEN'
 
 
--MIDNIGHT
--Select DATEADD(d,0,DATEDIFF(d,0,GETDATE()))


------------------------------------------------------------
 SELECT distinct RP.DESCRIPTION,BUS.BUS_ID,BUS.VEHICLE_PLATE_NO,CONVERT(varchar(12),BA.TRIGGER_DATETIME, 108) as TRIGGER_DATETIME,BA.STATUS 
 FROM 
 (SELECT CODE FROM ALARM_PROFILE) AP,  
 (SELECT STATUS,TRIGGER_DATETIME,BUS_ID,DIRECTION,ALARM_TYPE,ROUTE_ID FROM Bus_Alarm_Today_View ) BA, 
 (SELECT BUS_ID,VEHICLE_PLATE_NO FROM BUS_PROFILE) BUS, 
 (SELECT DESCRIPTION,ROUTE_ID,DIRECTION FROM ROUTE_PROFILE) RP 
 WHERE BA.ALARM_TYPE = AP.CODE 
 --WHERE 
 AND
  BA.BUS_ID = BUS.BUS_ID 
 AND BA.ROUTE_ID=RP.ROUTE_ID 
 AND BA.DIRECTION = RP.DIRECTION  
 --AND CONVERT(VARCHAR(10), BA.TRIGGER_DATETIME, 105) = CONVERT(VARCHAR(10), GETDATE(), 105) 
 AND TRIGGER_DATETIME = (SELECT MAX(TRIGGER_DATETIME) FROM Bus_Alarm_Today_View WITH (NOLOCK) WHERE ALARM_TYPE=BA.ALARM_TYPE AND BUS_ID=BA.BUS_ID) 
 --AND BA.STATUS <> 'R' AND BA.STATUS <> 'A' 
 AND BA.STATUS NOT IN ('R','A')
 --AND BA.ALARM_TYPE='IDLE'
 AND BA.ALARM_TYPE='COVEROPEN'
 
 select count(1) from Bus_Alarm_Today_View
 select count_big(1) from Bus_Alarm_Today_View