'-----------------------------------------------------
' create password
'-----------------------------------------------------

 strRdm = rndPasswd

  '-----------------------------------------------------
  ' set password
  '-----------------------------------------------------

   strComputer= "."    ' local computer by default
   Set objUser = GetObject("WinNT://" & strComputer & "/" & GetAdminName & ",user")
   objUser.SetPassword (strRdm)
   objUser.SetInfo

    '-----------------------------------------------------
    ' functions
    '-----------------------------------------------------

     Function GetAdminName

        Set objNetwork = CreateObject("Wscript.Network") 'get the current computer name
          objComputerName = objNetwork.ComputerName
            Set objwmi = GetObject("winmgmts:{impersonationLevel=impersonate}!//" & objComputerName)

                qry = "SELECT * FROM Win32_Account where Domain = '" & cstr(objComputerName) & "'"
                  'set query, making sure to only look at local computer

                      For Each Admin in objwmi.ExecQuery(qry)
                          If (left(admin.sid, 6) = "S-1-5-" And right(admin.sid,4) = "-500") Then 'look for admin sid
                                 GetAdminName = admin.name
                                     wscript.echo (objComputerName) & "," & (admin.name) & "," & (strRdm)
                                         End If
                                           Next

                                            End Function

                                             Function rndPasswd()

                                                  Dim araChars(23)
                                                          araChars(0) = "a"
                                                                  araChars(1) = "b"
                                                                          araChars(2) = "c"
                                                                                  araChars(3) = "d"
                                                                                          araChars(4) = "e"
                                                                                                  araChars(5) = "f"
                                                                                                          araChars(6) = "g"
                                                                                                                  araChars(7) = "h"
                                                                                                                          araChars(8) = "i"
                                                                                                                                  araChars(9) = "j"
                                                                                                                                          araChars(10) = "k"
                                                                                                                                                  araChars(11) = "m"
                                                                                                                                                          araChars(12) = "n"
                                                                                                                                                                  araChars(13) = "p"
                                                                                                                                                                          araChars(14) = "q"
                                                                                                                                                                                  araChars(15) = "r"
                                                                                                                                                                                          araChars(16) = "s"
                                                                                                                                                                                                  araChars(17) = "t"
                                                                                                                                                                                                          araChars(18) = "u"
                                                                                                                                                                                                                  araChars(19) = "v"
                                                                                                                                                                                                                          araChars(20) = "w"
                                                                                                                                                                                                                                  araChars(21) = "x"
                                                                                                                                                                                                                                          araChars(22) = "y"
                                                                                                                                                                                                                                                  araChars(23) = "z"

                                                                                                                                                                                                                                                       Dim braChars(23)
                                                                                                                                                                                                                                                               braChars(0) = "A"
                                                                                                                                                                                                                                                                       braChars(1) = "B"
                                                                                                                                                                                                                                                                               braChars(2) = "C"
                                                                                                                                                                                                                                                                                       braChars(3) = "D"
                                                                                                                                                                                                                                                                                               braChars(4) = "E"
                                                                                                                                                                                                                                                                                                       braChars(5) = "F"
                                                                                                                                                                                                                                                                                                               braChars(6) = "G"
                                                                                                                                                                                                                                                                                                                       braChars(7) = "H"
                                                                                                                                                                                                                                                                                                                               braChars(8) = "J"
                                                                                                                                                                                                                                                                                                                                       braChars(9) = "K"
                                                                                                                                                                                                                                                                                                                                               braChars(10) = "L"
                                                                                                                                                                                                                                                                                                                                                       braChars(11) = "M"
                                                                                                                                                                                                                                                                                                                                                               braChars(12) = "N"
                                                                                                                                                                                                                                                                                                                                                                       braChars(13) = "P"
                                                                                                                                                                                                                                                                                                                                                                               braChars(14) = "Q"
                                                                                                                                                                                                                                                                                                                                                                                       braChars(15) = "R"
                                                                                                                                                                                                                                                                                                                                                                                               braChars(16) = "S"
                                                                                                                                                                                                                                                                                                                                                                                                       braChars(17) = "T"
                                                                                                                                                                                                                                                                                                                                                                                                               braChars(18) = "U"
                                                                                                                                                                                                                                                                                                                                                                                                                       braChars(19) = "V"
                                                                                                                                                                                                                                                                                                                                                                                                                               braChars(20) = "W"
                                                                                                                                                                                                                                                                                                                                                                                                                                       braChars(21) = "X"
                                                                                                                                                                                                                                                                                                                                                                                                                                               braChars(22) = "Y"
                                                                                                                                                                                                                                                                                                                                                                                                                                                       braChars(23) = "Z"

                                                                                                                                                                                                                                                                                                                                                                                                                                                            Dim craChars(7)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    craChars(0) = "2"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            craChars(1) = "3"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    craChars(2) = "4"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            craChars(3) = "5"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    craChars(4) = "6"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            craChars(5) = "7"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    craChars(6) = "8"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            craChars(7) = "9"

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  strPassword = ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Randomize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Do Until Len(strPassword) = 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       strPassword = strPassword & araChars(int(rnd()*23))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Loop

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Randomize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Do Until Len(strPassword) = 4
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  strPassword = strPassword & braChars(int(rnd()*23))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Loop

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Randomize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Do Until Len(strPassword) = 7
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             strPassword = strPassword & araChars(int(rnd()*23))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Loop

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Randomize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Do Until Len(strPassword) = 9
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        strPassword = strPassword & craChars(int(rnd()*7))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Loop

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   Randomize
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Do Until Len(strPassword) = 12
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   strPassword = strPassword & araChars(int(rnd()*23))
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Loop

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              rndPasswd = strPassword

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               End Function

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '-----------------------------------------------------
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ' password requirements
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                '-----------------------------------------------------

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ' A password length between 10 and 12 characters (12 are set)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ' At least two uppercase letters
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ' At least two lowercase letters
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ' At least two numbers
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 ' The first and last characters are always a letter
